export enum Action{
    TOGGLE_CLICKED,
    REQUEST_FRAGMENT,
    WIDTH,
    CLOSE,
    HIDDEN,
    SHOWN,
    RESPONSE_FRAGMENT,
    NAVIGATE,
    SHOW,
    // REQUEST_ALREADY_SHOWN,
    // RESPONSE_ALREADY_SHOWN,
    BACKGROUND_READY
}